# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telara < Formula
  desc "Telara CLI — manage your MCP configurations"
  homepage "https://telara.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.0/Telara-CLI_0.1.0_darwin_amd64.tar.gz"
      sha256 "1bce0a707924362eeee3b268b9e0eae67ec184502cda952bd7650eec763e7052"

      define_method(:install) do
        bin.install "telara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.0/Telara-CLI_0.1.0_darwin_arm64.tar.gz"
      sha256 "2e00d476a050febab3b1ff042d53364fe29df51b69289a14bb0af6745ae185d1"

      define_method(:install) do
        bin.install "telara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.0/Telara-CLI_0.1.0_linux_amd64.tar.gz"
      sha256 "368726271e0d714ab162a001007ff93777bae454138c47d8adc859fcb59d1131"
      define_method(:install) do
        bin.install "telara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.0/Telara-CLI_0.1.0_linux_arm64.tar.gz"
      sha256 "495ae7bf77b34bdd02415f863dd61f433e89708b617d46673065ceb1c83a5e08"
      define_method(:install) do
        bin.install "telara"
      end
    end
  end

  test do
    system "#{bin}/telara version"
  end
end
