# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telara < Formula
  desc "Telara CLI — manage your MCP configurations"
  homepage "https://telara.dev"
  version "0.1.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.26/telara_0.1.26_darwin_amd64.tar.gz"
      sha256 "d1865ab392ef5c32741d4d95f232cabb2b729199fd91fe50e6a1c5ba5c62fe5e"

      define_method(:install) do
        bin.install "telara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.26/telara_0.1.26_darwin_arm64.tar.gz"
      sha256 "cc2deb9173730e425cc012507629e33355924697a50147d8bc9e5d993eef1628"

      define_method(:install) do
        bin.install "telara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.26/telara_0.1.26_linux_amd64.tar.gz"
      sha256 "a1cb72535ae0659de12e14e9abc4a2cf8045681501b207f9ec41429381f51921"
      define_method(:install) do
        bin.install "telara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Telara-Labs/Telara-CLI/releases/download/v0.1.26/telara_0.1.26_linux_arm64.tar.gz"
      sha256 "caf8dd481ed6e4782196d82b796e659d1d96f4767dd4a396cce7d47a4968ee1e"
      define_method(:install) do
        bin.install "telara"
      end
    end
  end

  test do
    system "#{bin}/telara version"
  end
end
